site_name: Media compatibility
site_url: https://example.test/docs/
theme:
  name: material
plugins:
- mkdocs-video:
    mark: shared
    is_video: true
    video_type: webm
- mkdocs-audio:
    mark: shared
    audio_type: wav
- search
markdown_extensions:
- attr_list
nav:
- Home: index.md
